# Generated by Django 4.2.4 on 2023-09-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_usershowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershowlist',
            name='episode_watched',
            field=models.IntegerField(default=0),
        ),
    ]
